version: '3.5'
services:
  mfcoind:
    image: mfcoin/mfcoind
    restart: always
    environment:
      - RPC_USER=mfcuser
      - RPC_PASSWORD=mfcpass
    volumes:
      - type: bind
        source: /opt/electrum/mfcoin/
        target: /home/mfcoin/.MFC/
    command:
      -nominting
      -printtoconsole
  electrumx:
    image: mfcoin/electrumx
    environment:
      - DAEMON_URL=mfcuser:mfcpass@mfcoind
      - COIN=MFCoin
      - DB_DIRECTORY=/data
      - CACHE_MB=400
      - SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
    volumes:
      - type: bind
        source: /opt/electrum/db/
        target: /data
    ports:
      - "50001:50001" # comment out to disable TCP port (plaintext)
      - "50002:50002"
      - "50004:50004"
      - "8000:8000"
    restart: always
    depends_on:
      - mfcoind
